kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data-pvc
  namespace: queue
  labels:
    app: mongodb
spec:
  storageClassName: main-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-config-pvc
  namespace: queue
  labels:
    app: mongodb
spec:
  storageClassName: main-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
