kind: Secret
apiVersion: v1
metadata:
  name: gateway-secret
  namespace: queue
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:pass@mongodb
  # mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo

  QUEUE_URI: amqp://admin:pass@rabbitmq
  # amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq
