kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  namespace: stream
  labels:
    app: redis
spec:
  storageClassName: main-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
