kind: Secret
apiVersion: v1
metadata:
  name: notification-secret
  namespace: queue
type: Opaque
stringData:
  EMAIL_ADDRESS: ""
  EMAIL_PASSWORD: ""

  QUEUE_URI: amqp://admin:pass@rabbitmq
  # amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq
