kind: Deployment
apiVersion: apps/v1
metadata:
  name: converter
  namespace: queue
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          imagePullPolicy: Never
          image: localhost/queue_converter
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
