kind: Secret
apiVersion: v1
metadata:
  name: auth-secret
  namespace: queue
type: Opaque
stringData:
  SUPERUSER_EMAIL: "YWRtaW5AZW1haWwuY29t" # "admin@email.com"
  SUPERUSER_PASSWORD: "cGFzcw==" # "pass"
  JWT_SECRET: c2VjcmV0 # secret

  DATABASE_URI: postgresql+psycopg2://admin:pass@postgres:5432/postgres
  # ${DB_DRIVERS}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}
