kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: queue
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: "/var/lib/rabbitmq"
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: queue
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 15672
    - name: amqp
      targetPort: amqp
      protocol: TCP
      port: 5672
